services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticketapp-sql
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecretPass123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketapp-api
    ports:
      - "5040:5040"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TicketAppDb;User Id=sa;Password=SuperSecretPass123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ticketapp-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  sql_data: